version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true
    steps: 
      - checkout

  test:
    machine:
        docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: |
            set -e
            cd tests
            docker-compose down --v
            docker-compose up --build tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - test